### ISSUE TITLE
Output formater

### ISSUE THREAD

**Issue by eviltik** [eviltik/evilscan#3]
* --console format (stdout output, stderr for progress infos, pipe separator) is partialy implemented
* --json is actualy fully implemented

Wondering more options like :
--screen (like the spec output of mocha)
--xml (if i really had nothing to do ...)

**Comment by mixmatch** [comment]
The documentation says default output is console but it seems to be json, even if i build options like:
      var scanOptions = {
          target:ip,
          port:'21-23,25,37,42,53,69,70,79,80,109,110,115,118,119,137,139,143,150,156,161,179,194,443,1900',
          status:'TROU', // Timeout, Refused, Open, Unreachable
          display: 'console',
          banner:true
      };

I am getting JSON output back.

**Comment by eviltik** [comment]
"display" option is only available when using evilscan as a command line tool.

When used in a node program, you format output like you want, example: 

```
scanner.on('result',function(data) {
        console.log('%s|%s|%s|%s',data.ip,data.port,data.banner,data.status);
});
```
