### ISSUE TITLE
IPv6 support [ need HELP ]

### ISSUE THREAD

**Issue by jesusprubio** [eviltik/evilscan#32]

**Comment by eviltik** [comment]
Huhuhu, please reopen this one in 2020/2022 !

**Comment by dsbaars** [comment]
It is 2022, please reopen :)

**Comment by eviltik** [comment]
PR Welcome 👯

**Comment by dsbaars** [comment]
> PR Welcome 👯

Implemented it, expect a PR soon.

**Comment by eviltik** [comment]
Nice shot ! Thank you.

I'd like to double check package deps before releasing a new version with your PR. Give me a few days.

**Comment by eviltik** [comment]
1.9.0 published

Thank you @dsbaars !
