### ISSUE TITLE
Call to q.run in evilscan.prototype.run failing

### ISSUE THREAD

**Issue by langdonx** [eviltik/evilscan#37]
es-test\node_modules\evilscan\main.js:388
        this.q.run();
              ^
    TypeError: Cannot read property 'run' of undefined
        at evilscan.run (es-test\node_modules\evilscan\main.js:388:11)

I ran into this using the test code provided in `README.md`.  Curiously enough I can run the cli tool installed through `npm install -g evilscan`.

    $ evilscan 127.0.0.1 --port=80

    127.0.0.1|80|open

From some light troubleshooting, it looks like the `async.series` callback from `options.parse` never executes, so `self.init` from main.js is never executed, so `this.q` is never defined.

**Comment by mixmatch** [comment]
I saw this issue recently and noticed that reverting some of the dependency packages made the issue go away... didn't troubleshoot enough to identify exactly which as several had been updated. Here's my working version of package.json:

  "dependencies": {
    "async": "1.0.0",
    "findup-sync": "0.2.1",
    "geoip-lite": "1.1.6",
    "optimist": "0.5.0",
    "printf": "0.2.1",
    "qjobs": "1.1.4",
    "winston": "1.0.0"
  }

**Comment by langdonx** [comment]
I fixed it temporarily by simply delaying `scanner.run`.

setTimeout(function() {
	scanner.run();
}, 1000);


You have to wrap it in a function, otherwise it doesn't get called a member.

**Comment by langdonx** [comment]
@mixmatch Ahh, nice.  async 1.0.0 fixes it.  Not sure what's changed there.

**Comment by eviltik** [comment]
thank you
