### ISSUE TITLE
weird scan results

### ISSUE THREAD

**Issue by roccomuso** [eviltik/evilscan#39]
When i send the command:

    evilscan 192.168.1.0/24

it returns me all the hosts from 192.168.1.1 to 192.168.1.255 ... what am i doing wrong? I'm on windows 10.

**Comment by kushalhalder** [comment]
I get the same thing when I use it as a node module.

**Comment by eviltik** [comment]
investigating ...

**Comment by eviltik** [comment]
it's because ports to scan should be mandatory. Fixing.

**Comment by eviltik** [comment]
so you have to evilscan 192.168.1.0/24 --port=80,22

etc

thank you for feedback
