### ISSUE TITLE
How to run a continuous scan with evilscan?

### ISSUE THREAD

**Issue by tomkubitza** [eviltik/evilscan#41]
Hi there,

I tried to run the scanner in a continuous way - by re-starting the scan (via scanner.run() ) within the "done" callback.

However, it seams the module is only made for a single scan, all subsequent calls of scanner.run() result in an immediate call of the "done" callback without having run a scan.

When I reinitialize the evilscan module for every new round, I run into another problem which gives the following output after 11 rounds:

```
(node) warning: possible EventEmitter memory leak detected. 11 SIGUSR2 listeners                                     added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.addListener (events.js:239:17)
```

After a few more rounds even the reinstantiation of the evilscan module is not working anymore (Does not scan anymore and throws the "done" callback immediately )

Any ideas on how to overcome this? :-)

I'm running it on a RPI2:
```
Linux rpi2 4.1.13-v7+ #826 SMP PREEMPT Fri Nov 13 20:19:03 GMT 2015 armv7l GNU/Linux
````

**Comment by eviltik** [comment]
My code is probably fucked (memory leak). So instead of waiting a complete refactor, i suggest you to use a fork (see nodejs Cluster module) https://nodejs.org/docs/latest/api/cluster.html

**Comment by cetfor** [comment]
Hey guys, I'm pretty late to the party here, but I wanted to shed some light on this issue and offer a solution to resolve it. 

As @tomkubitza found, running `scanner.run()` more than 10 times causes Node to display a MaxListenersExceededWarning warning:

 `(node:5876) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGUSR2 listeners added. Use emitter.setMaxListeners() to increase limit`

This is caused in `main.js` in the [`initQueuePause`](https://github.com/eviltik/evilscan/blob/master/main.js#L175) function. Inside this function, we add a new listener for 'SIGUSR2' to the Node global [`process`](https://nodejs.org/api/process.html#process_process).

If we end up adding more than `process.getMaxListeners()` (which defaults to 10) we get the warning about 11 'SIGUSR2' listeners added.  In fact, if you want to scan a /24 subnet (without 0 and 255), you'll end up adding 254 'SIGUSR2' listeners to `process`.

To avoid this issue, and not break the intended functionality of `initQueuePause`, I've wrapped the contents of `initQueuePause` with a check to see if the 'SIGUSR2' event is already registered.

`if (process.eventNames().indexOf('SIGUSR2') == -1) { ... }`

If you'd like more context, you can use `process.getMaxListeners()`, `process.eventNames()`, and `process.listenerCount('SIGUSR2')` to help debug the issue.  [Here's a Gist](https://gist.github.com/cetfor/86606393b3c04e8d9313e1d502c7c7fe) showing the fix I use.

Please let me know if you'd like me to submit a PR on this, @eviltik.  Thanks for making evilscan available, I've learned so much from it!

**Comment by eviltik** [comment]
@cetfor You win a beer 🥇 

evilscan 1.1.1 published
