### ISSUE TITLE
Error if you don't use a valid IP

### ISSUE THREAD

**Issue by michelem09** [eviltik/evilscan#42]
I receive this error if I try to use evilscan as module with a target different than a valid IP/Network address:

```
var evilscan = require('evilscan'),
                options = {
                    target: 'fhjgfjhfhf',
                    port: 22,
                    status: 'TROU',
                    banner: true,
                    display: 'json'
                },
                scanner = new evilscan(options);

scanner.run();
```

> node_modules/evilscan/main.js:390
>     this.q.run();
>           ^
> 
> TypeError: Cannot read property 'run' of undefined

**Comment by eviltik** [comment]
Thank you. Planning a full rewrite if this scanner.
