### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by gbaumgart** [eviltik/evilscan#43]
hi, 
when running global, I get : /usr/bin/env: ‘node\r’: No such file or directory

when checking the 'bin' /usr/local/bin/evilscan it turns out it has windows line endings. 

any plans to fix this for linux ?

**Comment by eviltik** [comment]
thank you !

bumping version for npm

**Comment by eviltik** [comment]
v1.0.3 available on npm
