### ISSUE TITLE
How do you scan the IPs ?

### ISSUE THREAD

**Issue by digits21** [eviltik/evilscan#47]
Hi , 
Thanks for the great work  !! could you tell me how to scan the ip addresses ? I can see that you are scanning ports in your Readme .  what if i want to scan ips ?

Thanks

**Comment by eviltik** [comment]
Hi

Thank you. Need to rewrite from scratch this poor and old code using ES6.

@digits21 I don't really understand your question. This scanner scan opened port of one or more IP Addresses, or range. So ... do you want just it give you if the IP reply to ICMP (ping) ?
