### ISSUE TITLE
SyntaxError: Block-scoped declarations

### ISSUE THREAD

**Issue by gitxmax** [eviltik/evilscan#51]
Hi,
When I tried running:
 evilscan xxx.xx.xxx.xxx --port=80 --banner

I get the following:

/usr/local/lib/node_modules/evilscan/bin/evilscan.js:14
    let scan = new evilscan(options);
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by eviltik** [comment]
Please provide your plateform and nodejs version

**Comment by eviltik** [comment]
Please confirme xxx.xx.xxx.xxx is a real IP addr in your test

**Comment by gitxmax** [comment]
The address is certainly a valid one.

 Ubuntu 16.04.4 LTS
nodejs: 4.2.6~dfsg-1ubuntu4.1

**Comment by eviltik** [comment]
@gitxmax node v4 ?? are you sure ? you are jocking ? 💃

**Comment by gitxmax** [comment]
that's what apt update && apt upgrade && apt install nodejs got me Today.
Anyways, installed nodejs manually, works now.
Thanks! ....
