### ISSUE TITLE
Very slow scan

### ISSUE THREAD

**Issue by gitxmax** [eviltik/evilscan#52]
Having issue with the scan speed, tried on 4 different servers, but the story is the same,
Sample: evilscan xx.xxx.xx.0/24 --port=1-10000 --concurrency 5000 --progress
every 1% takes about 2 minutes to scan,  --concurrency value doesn't seem to have any effect on the speed.
Tried "ulimit -u unlimited" command, with no positive result either.

**Comment by eviltik** [comment]
Probably. If you need the ultimate speed scanner, take a look at https://github.com/zmap/zmap

**Comment by guikubivan** [comment]
Same issue, I was thinking of using something like this for detecting microservices when developing locally, but it was too slow.
