### ISSUE TITLE
How do I scan more than one range at a time?

### ISSUE THREAD

**Issue by jfrux** [eviltik/evilscan#56]
Hilarious by the way:
https://github.com/eviltik/evilscan/blob/d311ea93432dfffcd1075d6a09ac2a64c1566997/libs/options.js#L233

Speaking of crazy people... any tips on how to fan out from the user's current IP based on a a rule?
Like I'd like to scan the network to a particular point... but having trouble understanding what to feed it.

For instance, I'd love to take the 3rd octet up and down 20 numbers or so and limit it to that?

**Comment by jfrux** [comment]
Basically I'm just trying to scan more than one range of IP's at a time...
`192.168.1.0 - 255, 192.168.2.0 - 255`

**Comment by eviltik** [comment]
It's not implemented and it will never be implemented. 

But you can do it yourself, just by using evilscan in parallel.
