### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by justintaddei** [eviltik/evilscan#58]
Updated electron and encountered this error:

`Uncaught TypeError: Cannot read property 'destroy' of undefined       .../TcpScan.js:121`

![devtools1](https://user-images.githubusercontent.com/16705594/51631104-6de2dc80-1f11-11e9-946d-8914206b59b2.jpg)

![devtools png](https://user-images.githubusercontent.com/16705594/51631167-979c0380-1f11-11e9-8b2a-eb1f6e0c958d.jpg)

Code to reproduce:
```javascript
const evilscan = require('evilscan')

var options = {
    target:'10.0.0.0/24',
    port: 9100,
    status:'O', // Timeout, Refused, Open, Unreachable
    banner:true
};

var scanner = new evilscan(options);
var dataArr = [];
scanner.on('result',function(data) {
    // fired when item is matching options
	dataArr.push(data);
    console.log(data);
});

scanner.on('error',function(err) {
    throw new Error(data.toString());
});

scanner.on('done',function() {
  	console.log('Done!', dataArr)
});

scanner.run();
```

This is my environment:

![devtools2](https://user-images.githubusercontent.com/16705594/51631267-db8f0880-1f11-11e9-944f-4ddefc353ba2.jpg)

If you need anything else to help fix this, let me know.

**Comment by eviltik** [comment]
thank you @justintaddei 

1.7.2 published

Perhaps 1.7.3 because of other npm packages update.

**Comment by eviltik** [comment]
Please wait. 1.7.3 on the road, but some tests fail with geoip

**Comment by eviltik** [comment]
1.7.3 published

**Comment by justintaddei** [comment]
Excellent. Will update when I get home.

Thank you for the quick response!
