### ISSUE TITLE
Problem with scanning by HOSTS

### ISSUE THREAD

**Issue by akhmdarya** [eviltik/evilscan#68]
Hello! Everything is ok with scanning by an IPs...by with host name it doesn't work.
Tell me, if I do something wrong:

   var options = {
      target:'google.com',
      port:'21-23',
      status:'TROU', // Timeout, Refused, Open, Unreachable
      banner:true,
     
  };

**Comment by eviltik** [comment]
hi,

i'll try to take a look today

**Comment by akhmdarya** [comment]
Thank you very much!

пн, 1 мар. 2021 г. в 18:02, eviltik <notifications@github.com>:

**Comment by eviltik** [comment]
It's work for me. But no result because no port 21/22/23 opened.

You can handle "done" event, see examples.
