### ISSUE TITLE
So ,  is it server side only ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [eviltik/evilscan#70]
Can't be used to map target network ? With just them visting the page ?

**Comment by eviltik** [comment]
What are you speaking about ?

Evilscan is a simple ip/port scanner. https://en.wikipedia.org/wiki/Port_scanner

**Comment by minanagehsalalma** [comment]
> What are you speaking about ?

I meant something like beEF



> Server side only yes.

Oh okay, thanks

**Comment by eviltik** [comment]
Like beef ?

![image](https://user-images.githubusercontent.com/4477890/110218885-72ce3480-7ebc-11eb-9b63-72e724d684c8.png)

:)

For readers  https://github.com/beefproject/beef
